language: ruby
rvm:
  - "2.1.1"

before_script:
  - psql -c 'create database upgrade_personal_site_test;' -U postgres

# test:
#   adapter: postgresql
#   database: upgrade_personal_site_test

# script:
# - RAILS_ENV=test bundle exec rake db:migrate --trace
# - bundle exec rake db:test:prepare
# - bundle exec rake
